-- MySQL Script generated by MySQL Workbench
-- 08/22/14 15:39:59
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema UniversityMySQL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UniversityMySQL` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `UniversityMySQL` ;

-- -----------------------------------------------------
-- Table `UniversityMySQL`.`Faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversityMySQL`.`Faculties` (
  `FacultyID` INT NOT NULL AUTO_INCREMENT,
  `FacultyName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`FacultyID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversityMySQL`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversityMySQL`.`Departments` (
  `DepartmentID` INT NOT NULL AUTO_INCREMENT,
  `DepartmentName` VARCHAR(45) NOT NULL,
  `FacultyID` INT NOT NULL,
  PRIMARY KEY (`DepartmentID`),
  INDEX `fk_Departments_Faculties_idx` (`FacultyID` ASC),
  CONSTRAINT `fk_Departments_Faculties`
    FOREIGN KEY (`FacultyID`)
    REFERENCES `UniversityMySQL`.`Faculties` (`FacultyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversityMySQL`.`Professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversityMySQL`.`Professors` (
  `ProfessorID` INT NOT NULL AUTO_INCREMENT,
  `ProfessorName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ProfessorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversityMySQL`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversityMySQL`.`Courses` (
  `CourseID` INT NOT NULL AUTO_INCREMENT,
  `CourseName` VARCHAR(45) NOT NULL,
  `DepartmentID` INT NOT NULL,
  `ProfessorID` INT NULL,
  PRIMARY KEY (`CourseID`),
  INDEX `fk_Courses_Departments1_idx` (`DepartmentID` ASC),
  INDEX `fk_Courses_Professors1_idx` (`ProfessorID` ASC),
  CONSTRAINT `fk_Courses_Departments1`
    FOREIGN KEY (`DepartmentID`)
    REFERENCES `UniversityMySQL`.`Departments` (`DepartmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_Professors1`
    FOREIGN KEY (`ProfessorID`)
    REFERENCES `UniversityMySQL`.`Professors` (`ProfessorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversityMySQL`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversityMySQL`.`Students` (
  `StudentID` INT NOT NULL AUTO_INCREMENT,
  `StudentName` VARCHAR(45) NOT NULL,
  `FacultyID` INT NULL,
  PRIMARY KEY (`StudentID`),
  INDEX `fk_Students_Faculties1_idx` (`FacultyID` ASC),
  CONSTRAINT `fk_Students_Faculties1`
    FOREIGN KEY (`FacultyID`)
    REFERENCES `UniversityMySQL`.`Faculties` (`FacultyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversityMySQL`.`ProfessorTitles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversityMySQL`.`ProfessorTitles` (
  `TitleID` INT NOT NULL AUTO_INCREMENT,
  `TitleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TitleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversityMySQL`.`CoursesStudents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversityMySQL`.`CoursesStudents` (
  `CourseID` INT NOT NULL,
  `StudentID` INT NOT NULL,
  INDEX `fk_CoursesStudents_Courses1_idx` (`CourseID` ASC),
  INDEX `fk_CoursesStudents_Students1_idx` (`StudentID` ASC),
  CONSTRAINT `fk_CoursesStudents_Courses1`
    FOREIGN KEY (`CourseID`)
    REFERENCES `UniversityMySQL`.`Courses` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CoursesStudents_Students1`
    FOREIGN KEY (`StudentID`)
    REFERENCES `UniversityMySQL`.`Students` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversityMySQL`.`ProfessorsTitlesAndProfessors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversityMySQL`.`ProfessorsTitlesAndProfessors` (
  `TitleID` INT NOT NULL,
  `ProfessorID` INT NOT NULL,
  INDEX `fk_ProfessorsTitles_Professors1_idx` (`TitleID` ASC),
  INDEX `fk_ProfessorsTitles_ProfessorTitles1_idx` (`ProfessorID` ASC),
  CONSTRAINT `fk_ProfessorsTitles_Professors1`
    FOREIGN KEY (`TitleID`)
    REFERENCES `UniversityMySQL`.`Professors` (`ProfessorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProfessorsTitles_ProfessorTitles1`
    FOREIGN KEY (`ProfessorID`)
    REFERENCES `UniversityMySQL`.`ProfessorTitles` (`TitleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
